remote_theme: pages themes/cayman@v0.2.0
# Luxury-Watches
«Кваліфікаційна робота на підтвердження ступеня фахового молодшого бакалавра (ВСП «ППФК НТУ «ХПІ»)
# Розробка Internet-магазину  «Luxury Watches»
Кваліфікаційна робота на підтвердження ступеня фахового молодшого  бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)).
Керівник роботи – Серебреннікова Ірина В’ячеславівна.
⎯ ## розроблений програмний продукт являє собою багатосторінковий Internet-магазин продажу преміальних годиників. Слід забезпечити стандартну для систем такого роду функціональність: оформлення та керування замовленнями, наявності товару, доступ до адміністративної панелі сайту. Використати інструментарій: Python, Bootstrap, MySQL.
